### ISSUE TITLE
Possible starting point

### ISSUE THREAD

**Issue by lawrencedark** [tonal-glyph/tgtracker#1]
@cmatsuoka is making a [mod player](https://github.com/cmatsuoka/0xd2) in Rust! Very exciting!

**Comment by cmatsuoka** [comment]
Hello @lawrencedark! There's a fundamental architectural issue at play when deciding whether a player engine would be used by a multi-format player, or a multi-format tracker (such as OpenMPT): is there a "master" internal editable format, or each format can use its own internal representation of data? The latter allows us to port original replayers for each format, but it doesn't seem very well suited for a tracker. On the other hand, having a single editable format and player that can handle replayer quirks to play different imported formats correctly is a big challenge too. Libxmp, for instance, evolved to the point it can play reasonably well, but fixing small compatibility problems is hard. Oxidrizzle, on the other hand, reached higher replayer accuracy levels very quickly, but each module is stored in-memory in a different format. For a tracker, you'll probably have to go for a single internal representation, and making the main formats (protracker, s3m, xm, it) work correctly could be quite hard!

**Comment by lawrencedark** [comment]
Hi @cmatsuoka That makes sense. Backwards compatibility should really be on the Nice-to-haves but fraught with issues section. This is also part of the reason why OpenMPT's codebase is so big.

**Comment by sm-Fifteen** [comment]
OpenMPT doesn't have that kind of internal format that's quirk-agnostic, all the logic to handle the various format and tracker differences is part of the audio rendering loop. Given that the point of the lib is to enable playback with (eventually) perfect accuracy, I can't fault them for that, but if you intend to use openmpt to read the raw pattern data for editing, OpenMPT won't really be of much help.

If you're just looking to use this for the player/visualizer part, though, the library has `highlight_pattern_row_channel` and `format_pattern_row_channel`, which print the format-specific representation. The Rust bindings for libopenmpt (which are all over the place in various aspects because I made that project to learn Rust and kinda ended up overusing a lot of language features in the wrong places) [expose those as part of the iteration stuff](https://docs.rs/openmpt/0.3.1/openmpt/module/iteration/struct.Cell.html#method.get_formatted), and you can then just query your current position using [these functions](https://docs.rs/openmpt/0.3.1/openmpt/module/struct.Module.html#method.get_current_order) (and I now realize their respective APIs have nothing in common).

**Comment by lawrencedark** [comment]
This is great advice. I need to decide if I'm making a tracker or a mod player. I think there are plenty of mod players, but not nearly enough trackers. Renoise has one editable format, but can import .XM, .IT, .MOD, and MIDI files. I think that's the ideal design if I can pull it off, but for now I'll focus on the tracker and my own format. Thank you both for your input.

**Comment by scalarwaves** [comment]
See #5 for my current starting point.
